config/routes.rb
Rails.application.routes.draw do
get 'admin' => 'admin#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

	resources :products do
  	get :who_bought, on: :member
	end

	root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_tag :body, class: controller.controller_name do %>

<div id="banner">
  <%= image_tag("logo.png") %>
  <%= @page_title || "Pragmatic Bookshelf" %>
</div>

	<div id="columns">
  <div id="side">
    <% if session[:user_id] %>
  <br />
  <%= link_to 'Orders',   orders_path   %><br />
  <%= link_to 'Products', products_path %><br />
  <%= link_to 'Users',    users_path    %><br />
  <br />
  <%= button_to 'Logout', logout_path, :method => :delete   %>
<% end %>
    <ul>
	<li><%= link_to "home",store_index_path %></li>
	<li><a href="http://www..../faq">Questions</a></li>
	<li><a href="http://www..../news">News</a></li>
	<li><a href="http://www..../contact">Contact</a></li>
	<li><%= @time %> </li>
	<% if @cart %>
	<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
		<%= render @cart %>
		
	<% end %>
	<%= button_to 'Empty cart', @cart, method: :delete,
      data: { confirm: 'Are you sure?' } %>
		<%= button_to 'Checkout', new_order_path, :method => :get %>
	<% end %>
    </ul>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
<% end %>

</body>
</html>